### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Kaery40** [Mansionme/getBuffDatas#2]
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python3.10.2\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Program Files (x86)\Python3.10.2\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Administrator\Desktop\getBuffDatas-main\GUI.py", line 7, in <module>
    import getCookie
  File "C:\Users\Administrator\Desktop\getBuffDatas-main\getCookie.py", line 2, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

**Comment by heyMahalo** [comment]
pip3 install webdriver_manager

**Comment by seadogbest** [comment]
您好大佬 请问下getcookie这里
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\github work\buff\getBuffDatas-main\GUI.py", line 121, in autoUpdate
    pwd = r1.split(",")[1]
IndexError: list index out of range
是什么原因啊

**Comment by heyMahalo** [comment]
你好，应该是输入不规范，电话号码和密码用逗号分开。可能你的逗号打成了全角符号？你可以尝试一下输出r1。
